language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
script:
- npm run test
after_success:
- chmod 700 ~/.ssh
- chmod 600 ~/.ssh/lfment
- ssh root@real.breakinferno.cn -o StrictHostKeyChecking=no 'cd ~/work/LFment-Server && git pull && ./ci.bash'
before_install:
- openssl aes-256-cbc -K $encrypted_570f11ecb315_key -iv $encrypted_570f11ecb315_iv
  -in lfment.enc -out ~/.ssh/lfment -d
# - openssl aes-256-cbc -K $encrypted_570f11ecb315_key -iv $encrypted_570f11ecb315_iv
#   -in id_rsa_lfment_server.enc -out ~/.ssh/id_rsa_lfment_server -d
